import { test, expect } from '@playwright/test';

// Generated by Playwright CLI Skill (Goose-style)
// Natural language prompt: "Go to example.com and click the Learn more link to navigate to IANA"

test('navigate from example.com to IANA via Learn more link', async ({ page }) => {
  // Step 1: Navigate to example.com
  await page.goto('https://example.com');
  await expect(page).toHaveTitle(/Example Domain/);

  // Step 2: Verify heading is present (ref: e3)
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Example Domain');

  // Step 3: Click "Learn more" link (ref: e6 in accessibility tree)
  await page.getByRole('link', { name: 'Learn more' }).click();

  // Step 4: Verify we landed on IANA example-domains page
  await expect(page).toHaveURL(/iana\.org\/help\/example-domains/);
  await expect(page).toHaveTitle(/Example Domains/);
});
