import { test, expect } from '@playwright/test';

// Generated by Goose AI Agent using Playwright CLI Skill
// Goose observed the accessibility tree (ref: e6 = "Learn more" link), 
// executed playwright-cli click e6, and assembled this test from the reported Playwright code

test.describe('Example Domain interactions', () => {
  test('navigate and interact with Example Domain page', async ({ page }) => {
    // Step 1: Open page — playwright-cli reported: await page.goto('https://example.com')
    await page.goto('https://example.com');
    await expect(page).toHaveTitle('Example Domain');

    // Step 5: Click "Learn more" — playwright-cli reported: await page.getByRole('link', { name: 'Learn more' }).click()
    await page.getByRole('link', { name: 'Learn more' }).click();

    // Verify navigation to IANA
    await expect(page).toHaveURL(/iana\.org\/help\/example-domains/);
    await expect(page).toHaveTitle('Example Domains');
  });
});
