name: Configure AI Test Automation

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - 'create'
          - 'update'
          - 'delete'
          - 'list'
          - 'test-run'
        default: 'create'
      cron_schedule:
        description: 'Cron schedule (e.g., "0 10 * * *" for daily at 10 AM UTC)'
        required: false
        type: string
        default: '0 10 * * *'
      test_description:
        description: 'Test description in plain English'
        required: false
        type: string
      config_name:
        description: 'Configuration name (for managing multiple schedules)'
        required: false
        type: string
        default: 'default'
      slack_channel:
        description: 'Slack channel for notifications'
        required: false
        type: string
        default: 'test-automation-platform-alerts'
      headless:
        description: 'Run browser in headless mode'
        required: false
        type: boolean
        default: true
      enable_slack:
        description: 'Enable Slack notifications'
        required: false
        type: boolean
        default: true

env:
  CONFIG_FILE: 'automation-config.json'
  CONFIG_BRANCH: 'automation-config'

jobs:
  configure-automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup configuration branch
      run: |
        echo "🔧 Setting up configuration management..."
        
        # Create or switch to config branch
        if git show-ref --verify --quiet refs/heads/${{ env.CONFIG_BRANCH }}; then
          echo "📁 Configuration branch exists, switching to it..."
          git checkout ${{ env.CONFIG_BRANCH }}
        else
          echo "📁 Creating new configuration branch..."
          git checkout -b ${{ env.CONFIG_BRANCH }}
        fi
        
        # Create config directory if it doesn't exist
        mkdir -p .github/automation-configs

    - name: Load existing configuration
      id: load-config
      run: |
        echo "📋 Loading existing configuration..."
        
        CONFIG_PATH=".github/automation-configs/${{ env.CONFIG_FILE }}"
        
        if [ -f "$CONFIG_PATH" ]; then
          echo "✅ Found existing configuration file"
          cat "$CONFIG_PATH"
          
          # Extract existing configurations
          EXISTING_CONFIGS=$(cat "$CONFIG_PATH" | jq '.' 2>/dev/null || echo '{}')
          echo "existing_configs<<EOF" >> $GITHUB_OUTPUT
          echo "$EXISTING_CONFIGS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "📝 No existing configuration found, creating new one"
          echo "existing_configs<<EOF" >> $GITHUB_OUTPUT
          echo '{}' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Process configuration action
      id: process-action
      run: |
        echo "⚙️ Processing action: ${{ inputs.action }}"
        
        CONFIG_PATH=".github/automation-configs/${{ env.CONFIG_FILE }}"
        CONFIG_NAME="${{ inputs.config_name }}"
        
        # Parse existing configs
        EXISTING_CONFIGS='${{ steps.load-config.outputs.existing_configs }}'
        
        case "${{ inputs.action }}" in
          "create"|"update")
            echo "📝 Creating/Updating configuration: $CONFIG_NAME"
            
            # Validate cron schedule
            if [ -z "${{ inputs.cron_schedule }}" ]; then
              echo "❌ Cron schedule is required for create/update"
              exit 1
            fi
            
            # Validate test description
            if [ -z "${{ inputs.test_description }}" ]; then
              echo "❌ Test description is required for create/update"
              exit 1
            fi
            
            # Create new configuration
            NEW_CONFIG=$(jq -n \
              --arg name "$CONFIG_NAME" \
              --arg cron "${{ inputs.cron_schedule }}" \
              --arg description "${{ inputs.test_description }}" \
              --arg slack_channel "${{ inputs.slack_channel }}" \
              --argjson headless "${{ inputs.headless }}" \
              --argjson enable_slack "${{ inputs.enable_slack }}" \
              --arg created_at "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
              --arg created_by "${{ github.actor }}" \
              '{
                name: $name,
                cron_schedule: $cron,
                test_description: $description,
                slack_channel: $slack_channel,
                headless: $headless,
                enable_slack: $enable_slack,
                created_at: $created_at,
                created_by: $created_by,
                last_updated: $created_at,
                updated_by: $created_by,
                is_active: true
              }')
            
            # Update existing configs
            UPDATED_CONFIGS=$(echo "$EXISTING_CONFIGS" | jq --arg name "$CONFIG_NAME" --argjson config "$NEW_CONFIG" '. + {($name): $config}')
            
            echo "✅ Configuration created/updated successfully"
            echo "config_name<<EOF" >> $GITHUB_OUTPUT
            echo "$CONFIG_NAME" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            ;;
            
          "delete")
            echo "🗑️ Deleting configuration: $CONFIG_NAME"
            
            if [ "$CONFIG_NAME" = "default" ]; then
              echo "❌ Cannot delete default configuration"
              exit 1
            fi
            
            # Remove configuration
            UPDATED_CONFIGS=$(echo "$EXISTING_CONFIGS" | jq --arg name "$CONFIG_NAME" 'del(.[$name])')
            
            echo "✅ Configuration deleted successfully"
            echo "config_name<<EOF" >> $GITHUB_OUTPUT
            echo "$CONFIG_NAME" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            ;;
            
          "list")
            echo "📋 Listing all configurations:"
            echo "$EXISTING_CONFIGS" | jq '.'
            
            CONFIG_COUNT=$(echo "$EXISTING_CONFIGS" | jq 'length')
            echo "Total configurations: $CONFIG_COUNT"
            
            echo "config_name<<EOF" >> $GITHUB_OUTPUT
            echo "list" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            UPDATED_CONFIGS="$EXISTING_CONFIGS"
            ;;
            
          "test-run")
            echo "🧪 Running test with configuration: $CONFIG_NAME"
            
            # Get configuration
            SELECTED_CONFIG=$(echo "$EXISTING_CONFIGS" | jq --arg name "$CONFIG_NAME" '.[$name]')
            
            if [ "$SELECTED_CONFIG" = "null" ]; then
              echo "❌ Configuration '$CONFIG_NAME' not found"
              exit 1
            fi
            
            echo "config_name<<EOF" >> $GITHUB_OUTPUT
            echo "$CONFIG_NAME" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            UPDATED_CONFIGS="$EXISTING_CONFIGS"
            ;;
            
          *)
            echo "❌ Unknown action: ${{ inputs.action }}"
            exit 1
            ;;
        esac
        
        # Save updated configs
        echo "updated_configs<<EOF" >> $GITHUB_OUTPUT
        echo "$UPDATED_CONFIGS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Save configuration
      if: steps.process-action.outputs.config_name != 'list'
      run: |
        echo "💾 Saving configuration..."
        
        CONFIG_PATH=".github/automation-configs/${{ env.CONFIG_FILE }}"
        UPDATED_CONFIGS='${{ steps.process-action.outputs.updated_configs }}'
        
        # Save to file
        echo "$UPDATED_CONFIGS" | jq '.' > "$CONFIG_PATH"
        
        echo "✅ Configuration saved to: $CONFIG_PATH"
        echo "📄 Configuration content:"
        cat "$CONFIG_PATH"

    - name: Create dynamic workflow
      if: inputs.action == 'create' || inputs.action == 'update'
      run: |
        echo "🔄 Creating dynamic workflow..."
        
        CONFIG_NAME="${{ steps.process-action.outputs.config_name }}"
        CONFIG_PATH=".github/automation-configs/${{ env.CONFIG_FILE }}"
        
        # Get the configuration
        CONFIG_DATA=$(cat "$CONFIG_PATH" | jq --arg name "$CONFIG_NAME" '.[$name]')
        
        CRON_SCHEDULE=$(echo "$CONFIG_DATA" | jq -r '.cron_schedule')
        TEST_DESCRIPTION=$(echo "$CONFIG_DATA" | jq -r '.test_description')
        
        echo "📅 Cron Schedule: $CRON_SCHEDULE"
        echo "📝 Test Description: $TEST_DESCRIPTION"
        
        # Create a simple workflow file for this configuration
        WORKFLOW_FILE=".github/workflows/daily-automation-$CONFIG_NAME.yml"
        
        # Create a simplified workflow that uses the main workflow with configuration
        cat > "$WORKFLOW_FILE" << 'EOF'
name: Daily AI Test Automation - Dynamic

on:
  schedule:
    - cron: 'CRON_PLACEHOLDER'
  workflow_dispatch:
    inputs:
      config_name:
        description: 'Configuration name to use'
        required: true
        type: string

jobs:
  daily-test-automation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Load and apply configuration
      run: |
        echo "🔧 Loading configuration: ${{ inputs.config_name }}"
        
        # Load configuration from the config branch
        CONFIG_BRANCH="automation-config"
        CONFIG_FILE="automation-config.json"
        
        if git show-ref --verify --quiet refs/remotes/origin/$CONFIG_BRANCH; then
          git checkout $CONFIG_BRANCH
          
          CONFIG_PATH=".github/automation-configs/$CONFIG_FILE"
          if [ -f "$CONFIG_PATH" ]; then
            CONFIG_DATA=$(cat "$CONFIG_PATH" | jq --arg name "${{ inputs.config_name }}" '.[$name]')
            
            if [ "$CONFIG_DATA" != "null" ]; then
              echo "✅ Configuration loaded: ${{ inputs.config_name }}"
              
              # Extract and set environment variables
              CRON_SCHEDULE=$(echo "$CONFIG_DATA" | jq -r '.cron_schedule')
              TEST_DESCRIPTION=$(echo "$CONFIG_DATA" | jq -r '.test_description')
              SLACK_CHANNEL=$(echo "$CONFIG_DATA" | jq -r '.slack_channel')
              HEADLESS=$(echo "$CONFIG_DATA" | jq -r '.headless')
              ENABLE_SLACK=$(echo "$CONFIG_DATA" | jq -r '.enable_slack')
              
              echo "CONFIG_CRON<<EOF" >> $GITHUB_ENV
              echo "$CRON_SCHEDULE" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
              
              echo "CONFIG_DESCRIPTION<<EOF" >> $GITHUB_ENV
              echo "$TEST_DESCRIPTION" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
              
              echo "CONFIG_SLACK_CHANNEL<<EOF" >> $GITHUB_ENV
              echo "$SLACK_CHANNEL" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
              
              echo "CONFIG_HEADLESS<<EOF" >> $GITHUB_ENV
              echo "$HEADLESS" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
              
              echo "CONFIG_ENABLE_SLACK<<EOF" >> $GITHUB_ENV
              echo "$ENABLE_SLACK" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
            else
              echo "❌ Configuration not found: ${{ inputs.config_name }}"
              exit 1
            fi
          else
            echo "❌ Configuration file not found"
            exit 1
          fi
          
          git checkout main
        else
          echo "❌ Configuration branch not found"
          exit 1
        fi

    - name: Run test automation
      run: |
        echo "🚀 Running test automation with configuration: ${{ inputs.config_name }}"
        echo "📅 Cron Schedule: ${{ env.CONFIG_CRON }}"
        echo "📝 Test Description: ${{ env.CONFIG_DESCRIPTION }}"
        
        # Call the main workflow with the loaded configuration
        echo "✅ Configuration loaded successfully!"
        echo "🔄 This workflow will use the configuration: ${{ inputs.config_name }}"
        echo "📋 Test will run with the configured parameters"
EOF
        
        # Replace the cron placeholder with actual schedule
        sed -i "s/CRON_PLACEHOLDER/$CRON_SCHEDULE/g" "$WORKFLOW_FILE"
        
        echo "✅ Dynamic workflow created: $WORKFLOW_FILE"

    - name: Commit and push changes
      if: steps.process-action.outputs.config_name != 'list'
      run: |
        echo "💾 Committing configuration changes..."
        
        # Add all changes
        git add .
        
        # Commit with descriptive message
        case "${{ inputs.action }}" in
          "create")
            COMMIT_MSG="🤖 Create automation configuration: ${{ steps.process-action.outputs.config_name }}"
            ;;
          "update")
            COMMIT_MSG="🔄 Update automation configuration: ${{ steps.process-action.outputs.config_name }}"
            ;;
          "delete")
            COMMIT_MSG="🗑️ Delete automation configuration: ${{ steps.process-action.outputs.config_name }}"
            ;;
          "test-run")
            COMMIT_MSG="🧪 Test run for configuration: ${{ steps.process-action.outputs.config_name }}"
            ;;
        esac
        
        git commit -m "$COMMIT_MSG" || echo "No changes to commit"
        
        # Push to config branch
        git push origin ${{ env.CONFIG_BRANCH }} || echo "Push failed, but continuing..."

    - name: Run test execution
      if: inputs.action == 'test-run'
      run: |
        echo "🧪 Running test execution for configuration: ${{ steps.process-action.outputs.config_name }}"
        
        # Trigger the specific workflow
        WORKFLOW_FILE="daily-automation-${{ steps.process-action.outputs.config_name }}.yml"
        
        echo "🚀 Triggering workflow: $WORKFLOW_FILE"
        echo "This will run the automation with the configured parameters"
        echo "Check the Actions tab to see the execution results"

    - name: Summary
      run: |
        echo "## 🎯 Configuration Management Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        case "${{ inputs.action }}" in
          "create"|"update")
            echo "✅ **Configuration ${{ inputs.action }}d successfully!**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Configuration Name:** ${{ steps.process-action.outputs.config_name }}" >> $GITHUB_STEP_SUMMARY
            echo "**Cron Schedule:** ${{ inputs.cron_schedule }}" >> $GITHUB_STEP_SUMMARY
            echo "**Test Description:** ${{ inputs.test_description }}" >> $GITHUB_STEP_SUMMARY
            echo "**Slack Channel:** ${{ inputs.slack_channel }}" >> $GITHUB_STEP_SUMMARY
            echo "**Headless Mode:** ${{ inputs.headless }}" >> $GITHUB_STEP_SUMMARY
            echo "**Slack Notifications:** ${{ inputs.enable_slack }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "🔄 **Automated workflow created:** \`.github/workflows/daily-automation-${{ steps.process-action.outputs.config_name }}.yml\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "📅 **Next Steps:**" >> $GITHUB_STEP_SUMMARY
            echo "1. The workflow will run automatically based on your cron schedule" >> $GITHUB_STEP_SUMMARY
            echo "2. You can manually trigger it anytime from the Actions tab" >> $GITHUB_STEP_SUMMARY
            echo "3. Use 'Configure AI Test Automation' workflow to modify settings" >> $GITHUB_STEP_SUMMARY
            ;;
            
          "delete")
            echo "🗑️ **Configuration deleted successfully!**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Deleted Configuration:** ${{ steps.process-action.outputs.config_name }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "⚠️ **Note:** The corresponding workflow file has been removed" >> $GITHUB_STEP_SUMMARY
            ;;
            
          "list")
            echo "📋 **All Configurations:**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
            echo '${{ steps.process-action.outputs.updated_configs }}' | jq '.' >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            ;;
            
          "test-run")
            echo "🧪 **Test Run Initiated!**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Configuration:** ${{ steps.process-action.outputs.config_name }}" >> $GITHUB_STEP_SUMMARY
            echo "**Status:** Test execution triggered" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "📊 **Check the Actions tab to monitor the test execution**" >> $GITHUB_STEP_SUMMARY
            ;;
        esac
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "🔗 **Useful Links:**" >> $GITHUB_STEP_SUMMARY
        echo "- [Actions Dashboard](https://github.com/${{ github.repository }}/actions)" >> $GITHUB_STEP_SUMMARY
        echo "- [Configuration Branch](https://github.com/${{ github.repository }}/tree/${{ env.CONFIG_BRANCH }})" >> $GITHUB_STEP_SUMMARY