name: Daily AI Test Automation - check

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      config_name:
        description: 'Configuration name to use'
        required: true
        type: string
        default: 'check'

permissions:
  contents: read
  actions: read

jobs:
  daily-test-automation:
    uses: ./.github/workflows/daily-test-automation.yml
    with:
      config_name: 'check'
    secrets: inherit
